Implement feature register and unitary test
jpcorreap/mercados-campesinos-app pull request #5
Opened 2021-08-04 01:53 UTC by LokiSchiffer

Going to merge the sqlite helper to do the registry on the local database, and implement the unitary test

2021-08-04 01:58 UTC, aapocode approved these changes
All fine!

2021-08-05 01:25 UTC, vivianachacon1 approved these changes
Good job !!!!

2021-08-05 03:10 UTC, jpcorreap requested changes

2021-08-05 03:10 UTC, jpcorreap commented on app/src/androidTest/java/com/equipo4/mercadoapp/ExampleInstrumentedTest.java
> +        assertEquals(rows, -1);
Si el test se llama insertUser debería validar únicamente eso, recomendaría separar este assertEquals en un test aparte.

2021-08-06 01:55 UTC, juansarmientog83 approved these changes
very well!!

2021-08-06 16:39 UTC, merged